plugins:
    - jekyll-coffeescript
    - jekyll-default-layout
    - jekyll-gist
    - jekyll-github-metadata
    - jekyll-optional-front-matter
    - jekyll-paginate
    - jekyll-readme-index
    - jekyll-relative-links
    - jekyll-titles-from-heading